[language-server.mylang-lsp]
command = "mylang-lsp"

[[language]]
name = "rust"
auto-format = true
language-servers = ["rls"]

[[language]]
auto-format = true
language-servers = ["pylsp"]
name = "python"
scope = "source.python"


[language-server.pylsp.config.plugins]
autopep8 = { enabled = false }
black = { enabled = true }
flake8 = { enabled = true }
mccabe = { enabled = false }
mypy = { enabled = true, live_mode = true, strict = true }
pycodestyle = { enabled = false }
pydocstyle = { enabled = false }
pyflakes = { enabled = false }
pylint = { enabled = false }
pyls_isort = { enabled = true }
rope_autoimport = { enabled = true }
yapf = { enabled = false }

