[rust]
language-servers = ["rust-analyzer"]
auto-format = true

[python]
language-servers = ["pylsp"]
auto-format = true

[go]
language-servers = ["gopls"]
auto-format = true

[json]
language-servers = ["vscode-json-language-server"]
auto-format = true

# [language-server.vscode-json-language-server]
# command = "vscode-json-language-server"
# args = ["--stdio"]
